FROM openjdk:17.0-jdk
RUN mkdir /APP
WORKDIR /APP
COPY EUAclient/target/euaService-0.0.1-SNAPSHOT.jar  /APP/euaService-0.0.1-SNAPSHOT.jar
COPY opentelemetry-javaagent.jar /APP/opentelemetry-javaagent.jar
EXPOSE 8901
ENV JAVA_TOOL_OPTIONS "-javaagent:/APP/opentelemetry-javaagent.jar"
RUN chmod -R 777 /APP
ENTRYPOINT ["java","-jar","/APP/euaService-0.0.1-SNAPSHOT.jar"]
