FROM openjdk:17.0-jdk
RUN mkdir /APP
WORKDIR /APP
COPY HSPA/target/hspa-0.0.1-SNAPSHOT.jar  /APP/hspa-0.0.1-SNAPSHOT.jar
COPY opentelemetry-javaagent.jar /APP/opentelemetry-javaagent.jar
EXPOSE 8084
ENV JAVA_TOOL_OPTIONS "-javaagent:/APP/opentelemetry-javaagent.jar"
RUN chmod -R 777 /APP
ENTRYPOINT ["java","-jar","/APP/hspa-0.0.1-SNAPSHOT.jar"]
