/*
 * Patient Health Record Service
 * Create your PHR ID to track your health records in one place.
 *
 * OpenAPI spec version: V.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package in.gov.abdm.eua.userManagement.dto.phr.registration;

import com.fasterxml.jackson.annotation.JsonInclude;
import in.gov.abdm.eua.userManagement.dto.phr.ServiceResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;
import java.util.Map;

/**
 * HidResponse
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString
@JsonInclude(JsonInclude.Include.NON_NULL)
public class HidResponse extends ServiceResponse {
    @NotNull(message = "sessionId cannot be null")
    private Object sessionId;

    @Valid
    @NotNull(message = "Name cannot be null")
    private HidName name;

    private Object gender;

    @Valid
    @NotNull(message = "DateOfBirth cannot be null")
    private HidDateOfBirth dateOfBirth;

    private Object healthIdNumber;

    private Object stateName;

    private Object address;

    private Object stateCode;

    private Object districtCode;

    private Object districtName;

    private Object pincode;

    private Object aadhaarVerified;

    private Object profilePhoto;

    private Object authMethods;

    private Object email;

    private Object mobile;

    private Object kycPhoto;

    private List<String> phrAddress;

    private Map<String, String> tags;

    private Object linkedPhrAddess;
    private Boolean kycVerified;
    private Object verificationStatus;
    private Object verificationType;
    private Object townName;
    private Boolean emailVerified;
    private Boolean mobileVerified;


}
