FROM openjdk:17.0-jdk
RUN mkdir /APP
WORKDIR /APP
COPY target/EUA-Gateway-0.0.1-SNAPSHOT.jar  /APP/EUA-Gateway-0.0.1-SNAPSHOT.jar
COPY opentelemetry-javaagent.jar /APP/opentelemetry-javaagent.jar
EXPOSE 8081
ENV JAVA_TOOL_OPTIONS "-javaagent:/APP/opentelemetry-javaagent.jar"
RUN chmod -R 777 /APP
ENTRYPOINT ["java","-jar","/APP/EUA-Gateway-0.0.1-SNAPSHOT.jar"]
